#!/bin/bash

set -e

nfs_mount_point="${HOME}/server_nfs_mount_2"
mkdir -p ${nfs_mount_point}

echo "Mount point at ${nfs_mount_point}"
sudo mount -t nfs kd-server:/bulk-storage/nfs/general ${nfs_mount_point}