#!/usr/bin/python3

import sys


class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


command_list = {
    "print_client_command": "print this list\n",

    "mount-server-nfs": "mount the server nfs share",
    "request-download-big-file 'url' 'file_name'": "Request the server to download big file, REMEMBER TO QUOTE THE URL AND NAME\n",

    "ssh-to-server": "ssh to the server"
}


def main() -> int:
    for cmd_name, cmd_note in command_list.items():
        print(f'{bcolors.WARNING}{cmd_name}{bcolors.ENDC}: {cmd_note}')

    print()

    return 0


if __name__ == '__main__':
    sys.exit(main())  # next section explains the use of sys.exit
