#!/usr/bin/python3

import sys


class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


command_list = {
    "print-client-command": "print this list\n",

    "mount-bulk-share": "mount the server nfs share at ~/server_nfs_mount",
    "list-nfs-file <tree_level>": "print a tree list of the files on the server, optionally specify the depth of the tree",
    "request-download-big-file 'url' 'file_name'": "Request the server to download big file, REMEMBER TO QUOTE THE URL AND NAME\n",

    "ssh-to-server": "ssh to the server\n",
    "vscode-ssh <path-on-server>": "create a vscode session to the server with the specified path",

    "request-buildroot-build <build_name>": "request a buildroot build to be done on the server",
    "list-ongoing-buildroot-build": "list all ongoing buildroot build",
}


def main() -> int:
    for cmd_name, cmd_note in command_list.items():
        print(f'{bcolors.WARNING}{cmd_name}{bcolors.ENDC}: {cmd_note}')

    print()

    return 0


if __name__ == '__main__':
    sys.exit(main())  # next section explains the use of sys.exit
