#!/bin/bash

source /bin/server_common.sh

set -e

if [ "$#" -lt 1 ]; then
    echo "usage: request-download-big-file '<url>' '[file_name]'"
    exit 1
fi

ssh -T ${kd_server_hostname} "download-big-file \"${1}\" \"${2}\""