#!/bin/bash
# usage:
# cd to root of a buildroot source
# do config and then save
# request-buildroot-build <build-name> [path-to-buildroot-config-folder]

source /bin/server_common.sh

set -e

if [ -z ${1} ]; then
    echo "Missing build name!"
    exit 1
fi
build_name="${1}"

config_dir="$(readlink -f .)"
if [ ! -z ${2} ]; then
    config_dir="$(readlink -f ${2})"
fi

echo "Using config from ${config_dir}"
cd ${config_dir}

timestamp=$(date "+%Y_%m_%d-%H_%M_%S")
config_dest_path="/tmp/config-${build_name}-${timestamp}"
buildroot_version="buildroot-$(make print-version)"

scp ./.config ${kd_server_hostname}:${config_dest_path}

ssh -T ${kd_server_hostname} "do-buildroot-build ${config_dest_path} ${build_name} ${buildroot_version}"