- hosts: "{{ variable_host | default('localhost') }}"
  tasks:
    - include: system_check.yml

    - include: bash/bash.yml
    - include: vscode/vscode.yml
    # - include: zsh/zsh.yml
    # - include: fish/fish.yml
    - include: misc/misc.yml
    - include: look/look.yml
    - include: snap/snap.yml
    - include: server/server.yml
    - include: client/client.yml