#!/bin/bash

source /bin/server_common.sh

function do_download
{
    nohup bash << END
        ln -sfv ${log_file} ${kd_ongoing_download_dir}/$(basename ${log_file})
        wget -q --show-progress --progress=dot:giga --output-document ${output_file_name} --content-disposition "${download_url}"

        rm -f ${kd_ongoing_download_dir}/$(basename ${log_file})
END
}

set -e

if [ "$#" -ne 2 ]; then
    echo "usage: download-big-file '<url>' '<file_name>'"
    exit 1
fi

download_url="${1}"
work_dir="${kd_big_file_storage}"
timestamp=$(date "+%Y_%m_%d-%H_%M_%S")
output_file_name="${2}"

log_file=${kd_download_log_dir}/download-big-file_${output_file_name}_${timestamp}.log

mkdir -p ${work_dir}
mkdir -p ${kd_ongoing_download_dir}
mkdir -p ${kd_download_log_dir}
cd ${work_dir}


echo "Log file at ${log_file}"

do_download > ${log_file} 2>&1 &