#!/bin/bash

function do_download
{
    nohup bash << END
        touch ${ongoing_download_dir}/${output_file_name}
        wget -q --show-progress --progress=dot:giga --output-document ${output_file_name} --content-disposition "${download_url}"

        rm -f ${ongoing_download_dir}/${output_file_name}
END
}

set -e

if [ "$#" -ne 2 ]; then
    echo "usage: download-big-file '<url>' '<file_name>'"
    exit 1
fi

download_url="${1}"
work_dir=/bulk-storage/nfs/general/big_file_storage
ongoing_download_dir=${work_dir}/ongoing_download
log_dir=${work_dir}/logs
timestamp=$(date "+%Y_%m_%d-%H_%M_%S")
output_file_name="${2}"

log_file=${log_dir}/download-big-file_${output_file_name}_${timestamp}.log

mkdir -p ${work_dir}
mkdir -p ${ongoing_download_dir}
mkdir -p ${log_dir}
cd ${work_dir}


echo "Log file at ${log_file}"

do_download > ${log_file} 2>&1 &