#!/usr/bin/python3

import sys


class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


command_list = {
    "print-server-command": "print this list\n",

    "download-big-file 'url' 'file_name'": "download big file, REMEMBER TO QUOTE THE URL AND NAME",
    "view-ongoing-download": "view logs of all the ongoing download\n",

    "stream-yocto-log": "view real-time yocto log, good for monitoring build",
    "view-yocto-log": "view entire yocto log, good for checking the entire build",
}


def main() -> int:
    print(f'{bcolors.OKCYAN}{bcolors.UNDERLINE}Server Commands:{bcolors.ENDC}')
    for cmd_name, cmd_note in command_list.items():
        print(f'{bcolors.WARNING}{cmd_name}{bcolors.ENDC}: {cmd_note}')

    print()

    return 0


if __name__ == '__main__':
    sys.exit(main())  # next section explains the use of sys.exit
