#!/bin/bash

function do_build
{
    nohup bash << END
        set -e
        function cleanup {
            rm -f ${guard_file}
        }
        trap cleanup EXIT

        echo "TIMESTAMP: ${timestamp}"

        cd ${yocto_cache_build_dir}
        bb_extra_arg=""

        if [ ! -z "${do_clean}" ]; then
            echo "Cleaning old build"
            rm -rf yocto_test
        fi

        if [ ! -z "${do_fetch}" ]; then
            echo "Will only fetch for this build"
            bb_extra_arg="${bb_extra_arg} --runall=fetch"
        fi

        if [ ! -d yocto_test ]; then
            git clone https://github.com/khoitd1997/yocto_test.git
        fi

        cd yocto_test
        git pull
        git submodule init
        git submodule update

        # TODO: Allow adjustment of build config
        ./set_build_config.sh debug

        # do a build first to set up all the necessary stuff
        set +e
        ./build.sh
        set -e
        . init_env.sh
        bitbake world --continue ${bb_extra_arg}
END
}

set -e

for var in "$@"; do
    if [ "${var}" = "--clean" ]; then
        do_clean=1
    elif [ "${var}" = "--fetch" ]; then
        do_fetch=1
    else
        echo "Unknown argument ${var}"
        exit 1
    fi
done

yocto_cache_build_dir="/bulk-storage/projects/yocto_cache"
log_file="${yocto_cache_build_dir}/log.txt"
guard_file="/tmp/.yocto_build_in_progress"
timestamp=$(date "+%Y_%m_%d-%H_%M_%S")

mkdir -p ${yocto_cache_build_dir}

if [ -f ${guard_file} ]; then
    echo "A build is already in progress! Exiting"
    exit 1
fi

touch ${guard_file}

echo "Cache refresh starting at ${yocto_cache_build_dir}"
do_build > ${log_file} 2>&1 &