- block:
    - name: setup repos
      shell: "{{item}}"
      with_items:
        - dnf install -q -y fedora-workstation-repositories
        - dnf install -q -y fedora-repos-modular
        - dnf install -q -y rpmfusion-free-release rpmfusion-nonfree-release rpmfusion-free-release-tainted rpmfusion-nonfree-release-tainted
        - dnf config-manager --set-enabled rpmfusion-nonfree-nvidia-driver google-chrome
        - dnf upgrade -q -y
      args:
        warn: false

    - include: ./install_packages.yml

  tags:
    - package
  become: true
