- block:
    - name: update system and enable repo
      shell: "{{item}}"
      with_items:
        - dnf install -q -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
        - dnf config-manager --add-repo https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
        - dnf config-manager --set-enabled virtualbox
        - dnf config-manager --set-enabled rpmfusion-nonfree-nvidia-driver google-chrome
        - dnf config-manager --set-enabled rpmfusion-free-updates rpmfusion-free
        - dnf config-manager --set-enabled rpmfusion-nonfree rpmfusion-nonfree-updates
        # - dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y -q
        - dnf groupupdate core -y
        - dnf upgrade -y -q
      args:
        warn: false

    - name: install packages
      shell: "{{item}}"
      with_items:
        - ./setup_packages.sh
      args:
        warn: false

    - name: install proprietary packages
      dnf:
        enablerepo: google-chrome rpmfusion-nonfree-nvidia-driver
        update_cache: yes
        state: present
        name:
          - google-chrome-stable
          - xorg-x11-drv-nvidia
          - akmod-nvidia
          - VirtualBox-6.0 # TODO: Recheck this in future
  tags:
    - package
  become: true
