- block:
    - name: create the /var/spool/slurmctld directory
      ansible.builtin.file:
        path: /var/spool/slurmctld
        mode: u=rwx,g=rx,o=x
        state: directory
        owner: slurm
        group: slurm
    - name: create /var/spool/slurmd directory
      ansible.builtin.file:
        path: /var/spool/slurmd
        mode: u=rwx,g=rx,o=x
        state: directory
        owner: slurm
        group: slurm

    - name: copy slurm config files to server
      register: slurm_conf
      copy:
        src: "{{ playbook_dir }}/server/slurm/slurm_conf/"
        dest: /etc/slurm-llnl
        mode: u=rwx,g=r,o=r
        owner: slurm
        group: slurm
    - name: restart slurmctld
      service:
        name: slurmctld
        enabled: yes
        state: restarted
      when: slurm_conf.changed
    - name: restart slurmd
      service:
        name: slurmd
        enabled: yes
        state: restarted
      when: slurm_conf.changed
    - name: enable Munge
      service:
        name: munge
        enabled: yes

    # NOTE: CAN ONLY BE RUN FROM THE SLURM SERVER
    # Munge key synchronization
    - tags:
        - munge-key
      when: 
        - kd_server_hostname == lookup("pipe","hostname")
        - munge_key_path is defined
      block:
        - name: copy Munge key
          register: munge_key
          copy:
            src: "{{ munge_key_path }}"
            dest: /etc/munge/munge.key
            mode: u=r,g=,o=
            owner: munge
            group: munge
        - name: restart Munge
          service:
            name: munge
            enabled: yes
            state: restarted
          when: munge_key.changed

  become: true
  tags:
    - server_slurm
    - slurm
