- vars:
    nfs_dir: "/bulk-storage/nfs/general"

  block:
  - name: start nfs server
    service:
      name: nfs-kernel-server
      state: started

  - name: create the nfs directory
    ansible.builtin.file:
      path: "{{ nfs_dir }}"
      recurse: yes
      mode: u+rwx,g+rwx,o-rwx
      owner: nobody
      group: kd-nfs
      state: directory

  - name: configure nfs server export
    register: nfs_export_conf
    blockinfile:
      path: /etc/exports
      block: |
        {{ nfs_dir }}       kd-*(rw,sync,no_subtree_check)
  - name: restart nfs server if needed
    service:
      name: nfs-kernel-server
      state: restarted
    when: nfs_export_conf.changed