- tags:
  - server
  - never

  block:
    - name: install server deb packages
      apt:
        update_cache: yes
        state: present
        dpkg_options: "force-overwrite,force-confdef,force-confold" 
        name:
          - nfs-kernel-server
          - openssh-server

    - name: Set server hostname
      ansible.builtin.hostname:
        name: "{{ server_hostname }}"

    # TODO: PXE/tftp
    # https://github.com/awesome-selfhosted/awesome-selfhosted
    - include: sshd.yml
    - include: nfs.yml
    - include: ufw.yml
    - include: custom_server_scripts/custom_server_scripts.yml

  become: true
